### ISSUE TITLE
Moving from OkHttpClient to Apache HttpClient

### ISSUE THREAD

**Issue by koushikr** [appform-io/ranger#28]
Move from the current OkHttpClient to Apache HttpClient, and use a single instance of it across, rather than creating a new instance every time. 

One proposal is, wherever the OkHttpClient is used, say in HttpNodeDataSource, dataSink and so on, use a container class called, HttpExecutor and create this HttpExecutor right in the RangerHttpClient and AbstractRangerHttpHubClient respectively, from their start methods. 

Keeps the interfaces clean and changes minimal and testable.

**Comment by santanusinha** [comment]
The new HttpComponents interface is similar to what you are saying .. ithink it will significantly clean up the code. Looking fwd to this...

**Comment by koushikr** [comment]
@pranithk is picking it up.
